# ESAME FINE MODULO PYTHON MELISSA NORA

Analisi diffusione COVID-19 nel mondo 

Il committente richiede di avere un report su casi e vaccinazioni in diverse aree del mondo; a tal fine, richiede di utilizzare il dataset, curato da Our World in Data, all'indirizzo https://github.com/owid/covid-19-data/tree/master/public/data;  alla voce "ðŸ—‚ Download our complete COVID-19 dataset" scaricare il dataset in formato CSV oppure in formato JSON. 

â€¢Si richiede di verificare le dimensioni del dataset e le diciture presenti nell'intestazione; 

â€¢Si chiede poi per ogni continente di trovare il numero di casi totali avvenuti in quello stesso continente; si chiede di non considerare eventuali locazioni che nel dataset non appartengono ad alcun continente; 

â€¢Sempre riguardo i casi di COVID totali, si chiede di sviluppare una funzione che prenda in input il dataset e due nomi di continenti, e che ne confronti i seguenti relativi descrittori statistici: valori minimo e massimo, media, e percentuale rispetto al numero dei casi totali nel mondo (calcolati anche sulle locazioni senza indicazione di continente); 

â€¢Si chiede poi di effettuare lo stesso tipo di analisi â€“ anche in questo caso sviluppando una funzione ad hoc â€“ per il numero di vaccinazioni totali per ogni continente; 

â€¢Alla fine, basandosi sui calcoli fatti, il committente chiede di stilare un breve (tre o quattro righe) paragrafo testuale riassuntivo sulle statistiche di casi e vaccinazioni, che si concentri solo sulle differenze esistenti tra Europa, Sud America e Oceania.

In [21]:
import pandas as pd # importo pandas

In [35]:
file_covid = "F:/EPICODE/owid-covid-data.csv" #carico CSV dal mio PC

â€¢Si richiede di verificare le dimensioni del dataset e le diciture presenti nell'intestazione;

In [66]:
struttura = pd.read_csv(file_covid, sep=',', header=0, dtype=str, low_memory=False) 

# metto il dataset in una variabile per poterlo leggere, imposto la prima riga come hearder

print(struttura) # stampa il dataset

       iso_code continent     location        date total_cases new_cases  \
0           AFG      Asia  Afghanistan  2020-01-05         NaN       0.0
1           AFG      Asia  Afghanistan  2020-01-06         NaN       0.0
2           AFG      Asia  Afghanistan  2020-01-07         NaN       0.0
3           AFG      Asia  Afghanistan  2020-01-08         NaN       0.0
4           AFG      Asia  Afghanistan  2020-01-09         NaN       0.0
...         ...       ...          ...         ...         ...       ...
376980      ZWE    Africa     Zimbabwe  2024-01-31    266265.0       0.0
376981      ZWE    Africa     Zimbabwe  2024-02-01    266265.0       0.0
376982      ZWE    Africa     Zimbabwe  2024-02-02    266265.0       0.0
376983      ZWE    Africa     Zimbabwe  2024-02-03    266265.0       0.0
376984      ZWE    Africa     Zimbabwe  2024-02-04    266265.0       0.0

       new_cases_smoothed total_deaths new_deaths new_deaths_smoothed  ...  \
0                     NaN          NaN        0.0                 NaN  ...
1                     NaN          NaN        0.0                 NaN  ...
2                     NaN          NaN        0.0                 NaN  ...
3                     NaN          NaN        0.0                 NaN  ...
4                     NaN          NaN        0.0                 NaN  ...
...                   ...          ...        ...                 ...  ...
376980              4.429       5737.0        0.0                 0.0  ...
376981              4.429       5737.0        0.0                 0.0  ...
376982              4.429       5737.0        0.0                 0.0  ...
376983              4.429       5737.0        0.0                 0.0  ...
376984                0.0       5737.0        0.0                 0.0  ...

       male_smokers handwashing_facilities hospital_beds_per_thousand  \
0               NaN                 37.746                        0.5
1               NaN                 37.746                        0.5
2               NaN                 37.746                        0.5
3               NaN                 37.746                        0.5
4               NaN                 37.746                        0.5
...             ...                    ...                        ...
376980         30.7                 36.791                        1.7
376981         30.7                 36.791                        1.7
376982         30.7                 36.791                        1.7
376983         30.7                 36.791                        1.7
376984         30.7                 36.791                        1.7

       life_expectancy human_development_index  population  \
0                64.83                   0.511  41128772.0
1                64.83                   0.511  41128772.0
2                64.83                   0.511  41128772.0
3                64.83                   0.511  41128772.0
4                64.83                   0.511  41128772.0
...                ...                     ...         ...
376980           61.49                   0.571  16320539.0
376981           61.49                   0.571  16320539.0
376982           61.49                   0.571  16320539.0
376983           61.49                   0.571  16320539.0
376984           61.49                   0.571  16320539.0

       excess_mortality_cumulative_absolute excess_mortality_cumulative  \
0                                       NaN                         NaN
1                                       NaN                         NaN
2                                       NaN                         NaN
3                                       NaN                         NaN
4                                       NaN                         NaN
...                                     ...                         ...
376980                                  NaN                         NaN
376981                                  NaN                         NaN
376982                                  NaN                         NaN
376983                                  NaN                         NaN
376984                                  NaN                         NaN

       excess_mortality excess_mortality_cumulative_per_million
0                   NaN                                     NaN
1                   NaN                                     NaN
2                   NaN                                     NaN
3                   NaN                                     NaN
4                   NaN                                     NaN
...                 ...                                     ...
376980              NaN                                     NaN
376981              NaN                                     NaN
376982              NaN                                     NaN
376983              NaN                                     NaN
376984              NaN                                     NaN

[376985 rows x 67 columns]

In [38]:
struttura.shape # il dataser ha 376985 righe e 67 colonne

(376985, 67)

In [39]:
struttura.sample (10) # mi studio 10 records causali

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,population,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
113436,FRA,Europe,France,2020-01-27,3.0,0.0,0.429,NaN,0.0,0.0,...,35.6,NaN,5.98,82.66,0.901,67813000.0,NaN,NaN,NaN,NaN
354691,GBR,Europe,United Kingdom,2023-08-29,24685994.0,0.0,1284.0,229674.0,0.0,32.571,...,24.7,NaN,2.54,81.32,0.932,67508936.0,NaN,NaN,NaN,NaN
104015,ETH,Africa,Ethiopia,2022-12-21,496083.0,0.0,126.714,7572.0,0.0,0.0,...,8.5,7.96,0.3,66.6,0.485,123379928.0,NaN,NaN,NaN,NaN
287488,SPM,North America,Saint Pierre and Miquelon,2022-08-19,3131.0,0.0,2.714,1.0,0.0,0.0,...,NaN,NaN,NaN,81.07,NaN,5885.0,NaN,NaN,NaN,NaN
31083,BLR,Europe,Belarus,2023-04-18,994037.0,0.0,0.0,7118.0,0.0,0.0,...,46.1,NaN,11.0,74.79,0.823,9534956.0,NaN,NaN,NaN,NaN
46866,VGB,North America,British Virgin Islands,2021-07-21,2024.0,0.0,125.286,12.0,0.0,1.286,...,NaN,NaN,NaN,79.07,NaN,31332.0,NaN,NaN,NaN,NaN
6955,ASM,Oceania,American Samoa,2022-09-18,8235.0,18.0,2.571,34.0,0.0,0.0,...,NaN,NaN,NaN,73.74,NaN,44295.0,NaN,NaN,NaN,NaN
191746,OWID_LMC,NaN,Lower middle income,2021-11-23,63572291.0,0.0,53768.429,1135157.0,0.0,1580.857,...,NaN,NaN,NaN,NaN,NaN,3432097300.0,NaN,NaN,NaN,NaN
182893,LSO,Africa,Lesotho,2022-03-19,32775.0,0.0,8.429,697.0,0.0,0.0,...,53.9,2.117,NaN,54.33,0.527,2305826.0,NaN,NaN,NaN,NaN
40787,BES,North America,Bonaire Sint Eustatius and Saba,2021-04-01,1247.0,0.0,43.143,10.0,0.0,0.571,...,NaN,NaN,NaN,77.79,NaN,27052.0,NaN,NaN,NaN,NaN

In [46]:
colonne = list(struttura.columns) 
colonne_vert = '\n'.join(colonne) # perchÃ¨ le voglio stampate in verticale
print (colonne_vert)

iso_code
continent
location
date
total_cases
new_cases
new_cases_smoothed
total_deaths
new_deaths
new_deaths_smoothed
total_cases_per_million
new_cases_per_million
new_cases_smoothed_per_million
total_deaths_per_million
new_deaths_per_million
new_deaths_smoothed_per_million
reproduction_rate
icu_patients
icu_patients_per_million
hosp_patients
hosp_patients_per_million
weekly_icu_admissions
weekly_icu_admissions_per_million
weekly_hosp_admissions
weekly_hosp_admissions_per_million
total_tests
new_tests
total_tests_per_thousand
new_tests_per_thousand
new_tests_smoothed
new_tests_smoothed_per_thousand
positive_rate
tests_per_case
tests_units
total_vaccinations
people_vaccinated
people_fully_vaccinated
total_boosters
new_vaccinations
new_vaccinations_smoothed
total_vaccinations_per_hundred
people_vaccinated_per_hundred
people_fully_vaccinated_per_hundred
total_boosters_per_hundred
new_vaccinations_smoothed_per_million
new_people_vaccinated_smoothed
new_people_vaccinated_smoothed_per_hundred
stringency_index
population_density
median_age
aged_65_older
aged_70_older
gdp_per_capita
extreme_poverty
cardiovasc_death_rate
diabetes_prevalence
female_smokers
male_smokers
handwashing_facilities
hospital_beds_per_thousand
life_expectancy
human_development_index
population
excess_mortality_cumulative_absolute
excess_mortality_cumulative
excess_mortality
excess_mortality_cumulative_per_million

â€¢Si chiede poi per ogni continente di trovare il numero di casi totali avvenuti in quello stesso continente; si chiede di non considerare eventuali locazioni che nel dataset non appartengono ad alcun continente;

In [79]:
# ho bisogno di convertire la colonna dei casi in numerico 
struttura['total_cases'] = pd.to_numeric(struttura['total_cases'], errors='coerce')

# tolgo tutti i nulli in continent
struttura_continente = struttura.dropna(subset=['continent'])

# Raggruppa i dati per continente e trova il massimo dei casi totali per ogni continente
casi_per_continente = struttura_continente.groupby('continent')['total_cases'].max().reset_index()
# mi sono presa il massimo perchÃ¨ essendo continent un incrementale l'ultima data sarÃ  giÃ  una somma di tutti i casi

       continent  total_cases
0         Africa    4072636.0
1           Asia   99329249.0
2         Europe   38997490.0
3  North America  103436829.0
4        Oceania   11769858.0
5  South America   37519960.0

â€¢Sempre riguardo i casi di COVID totali, si chiede di sviluppare una funzione che prenda in input il dataset e due nomi di continenti, e che ne confronti i seguenti relativi descrittori statistici: valori minimo e massimo, media, e percentuale rispetto al numero dei casi totali nel mondo (calcolati anche sulle locazioni senza indicazione di continente);

In [133]:

'''voglio una funzione che dia la possibilitÃ  di scegliere due contenti 
in base al continente scelto nella colonna continenti di struttura_continente mi
dia in output min, max, mean e percentuale dei casi '''

# due input 
# total cases
# descrizione statistica: min, max, mean, percent tot casi nel mondo) 

def confronta_continenti(struttura, continente1, continente2):
   #lavoro prima sul continente 1 
    # Filtro il dataset per includere solo i casi relativi al continente1 specificati
    casi_continente1= struttura[struttura['continent'] == continente1]['total_cases']

    # mi calcolo i dati statistici su continente1
    minimo_continente1 = casi_continente1.min()
    massimo_continente1 = casi_continente1.max()
    media_continente1 = casi_continente1.mean()
    # uso la somma dei nuovi casi (non uso total case perchÃ¨ Ã¨ incrementale) come variabile 
    # ho dovuvo impostare new cases come numerico 
    struttura['new_cases'] = pd.to_numeric(struttura['new_cases'], errors='coerce')
    casi_totali_mondo = struttura['new_cases'].sum()
    # Calcolo le percentuali rispetto ai casi totali nel mondo per continente1
    casi_continente1_1= struttura[struttura['continent'] == continente1]['new_cases']
    percentuale_continente1 = (casi_continente1_1.sum() / casi_totali_mondo) * 100
    
    #ripeto tutto su continente 2 
    # Filtro il dataset per includere solo i casi relativi al continente2 specificati
    casi_continente2 = struttura[struttura['continent'] == continente2]['total_cases']
    # mi calcolo i dati statistici su continente2
    minimo_continente2 = casi_continente2.min()
    massimo_continente2 = casi_continente2.max()
    media_continente2 = casi_continente2.mean()
    
    # Calcolo le percentuali rispetto ai casi totali nel mondo per continente2
    casi_continente2_2 = struttura[struttura['continent'] == continente2]['new_cases']
    percentuale_continente2 = (casi_continente2_2.sum() / casi_totali_mondo) * 100
    print("Il min di casi in", continente1, "Ã¨", minimo_continente1)
    print("Il min di casi in", continente2, "Ã¨", minimo_continente2)
    print("Il max di casi in", continente1, "Ã¨", massimo_continente1)
    print("Il max di casi in", continente2, "Ã¨", massimo_continente2)       
    print("La media dei casi in", continente1, "Ã¨", media_continente1)
    print("La media dei casi in", continente2, "Ã¨", media_continente2)  
    print("La percentuale dei casi in", continente1, "Ã¨", percentuale_continente1)
    print("La percentuale dei casi in", continente2, "Ã¨", percentuale_continente2)

In [134]:

confronta_continenti(struttura, 'Europe', 'South America')

Il min di casi in Europe Ã¨ 1.0
Il min di casi in South America Ã¨ 1.0
Il max di casi in Europe Ã¨ 38997490.0
Il max di casi in South America Ã¨ 37519960.0
La media dei casi in Europe Ã¨ 2602675.778776635
La media dei casi in South America Ã¨ 3056576.174385965
La percentuale dei casi in Europe Ã¨ 7.677358236403552
La percentuale dei casi in South America Ã¨ 2.0944909462884502

esempio Europa e Sud America:

Il min di casi in Europe Ã¨ 1.0

Il min di casi in South America Ã¨ 1.0

Il max di casi in Europe Ã¨ 38997490.0

Il max di casi in South America Ã¨ 37519960.0

La media dei casi in Europe Ã¨ 2602675.778776635

La media dei casi in South America Ã¨ 3056576.174385965

La percentuale dei casi in Europe Ã¨ 7.7%

La percentuale dei casi in South America Ã¨ 2.1%

â€¢Si chiede poi di effettuare lo stesso tipo di analisi â€“ anche in questo caso sviluppando una funzione ad hoc â€“ per il numero di vaccinazioni totali per ogni continente;

In [123]:
#basandomi sulla funzione di prima volevo che si ptoessero inserire piÃ¹ di due continenti selezionati 

def confronta_vaccinazioni_continenti2(struttura, *continenti):
    for continente in continenti:
        struttura['total_vaccinations'] = pd.to_numeric(struttura['total_vaccinations'], errors='coerce')
    
        vaccinazioni_continente = struttura[struttura['continent'] == continente]['total_vaccinations']

        min_vax_continente = vaccinazioni_continente.min()
        max_vax_continente = vaccinazioni_continente.max()
        mean_vax_continente = vaccinazioni_continente.mean()
        vax_totali_mondo = struttura['total_vaccinations'].sum()
        percentuale_vax_continente = (vaccinazioni_continente.sum() / vax_totali_mondo) * 100
    

        print("Il min dei vaccini in", continente, "Ã¨", min_vax_continente)
        print("Il max dei vaccini in", continente, "Ã¨", max_vax_continente)     
        print("La media dei vaccini in", continente, "Ã¨", mean_vax_continente)
        print("La percentuale dei vaccini in", continente, "Ã¨", percentuale_vax_continente)

In [124]:
# prova per vedere se la funzione funzioni
confronta_vaccinazioni_continenti2 (struttura, 'Europe', 'South America', 'Asia')

Il min dei vaccini in Europe Ã¨ 0.0
Il max dei vaccini in Europe Ã¨ 192221468.0
La media dei vaccini in Europe Ã¨ 27275774.196870532
La percentuale dei vaccini in Europe Ã¨ 1.782823009422204
Il min dei vaccini in South America Ã¨ 0.0
Il max dei vaccini in South America Ã¨ 486436436.0
La media dei vaccini in South America Ã¨ 65958353.543699816
La percentuale dei vaccini in South America Ã¨ 1.0501583501770269
Il min dei vaccini in Asia Ã¨ 0.0
Il max dei vaccini in Asia Ã¨ 3491077000.0
La media dei vaccini in Asia Ã¨ 230728539.32374448
La percentuale dei vaccini in Asia Ã¨ 10.628684534264309

â€¢Alla fine, basandosi sui calcoli fatti, il committente chiede di stilare un breve (tre o quattro righe) paragrafo testuale riassuntivo sulle statistiche di casi e vaccinazioni, che si concentri solo sulle differenze esistenti tra Europa, Sud America e Oceania.

In [125]:
confronta_vaccinazioni_continenti2 (struttura, 'Europe', 'South America', 'Oceania')

Il min dei vaccini in Europe Ã¨ 0.0
Il max dei vaccini in Europe Ã¨ 192221468.0
La media dei vaccini in Europe Ã¨ 27275774.196870532
La percentuale dei vaccini in Europe Ã¨ 1.782823009422204
Il min dei vaccini in South America Ã¨ 0.0
Il max dei vaccini in South America Ã¨ 486436436.0
La media dei vaccini in South America Ã¨ 65958353.543699816
La percentuale dei vaccini in South America Ã¨ 1.0501583501770269
Il min dei vaccini in Oceania Ã¨ 0.0
Il max dei vaccini in Oceania Ã¨ 69306345.0
La media dei vaccini in Oceania Ã¨ 12617372.973786408
La percentuale dei vaccini in Oceania Ã¨ 0.0639019785567765

In [135]:
confronta_continenti(struttura, 'Europe', 'Oceania')

Il min di casi in Europe Ã¨ 1.0
Il min di casi in Oceania Ã¨ 1.0
Il max di casi in Europe Ã¨ 38997490.0
Il max di casi in Oceania Ã¨ 11769858.0
La media dei casi in Europe Ã¨ 2602675.778776635
La media dei casi in Oceania Ã¨ 355420.45812
La percentuale dei casi in Europe Ã¨ 7.677358236403552
La percentuale dei casi in Oceania Ã¨ 0.4490935565090396

# CASI

EUROPA

Il min di casi in Europe Ã¨ 1.0

Il max di casi in Europe Ã¨ 38997490.0

La media dei casi in Europe Ã¨ 2602675.778776635

La percentuale dei casi in Europe Ã¨ 8%


SUD AMERICA

Il min di casi in South America Ã¨ 1.0

Il max di casi in South America Ã¨ 37519960.0

La media dei casi in South America Ã¨ 3056576.174385965

La percentuale dei casi in South America Ã¨ 2%


OCEANIA

Il min di casi in Oceania Ã¨ 1.0

Il max di casi in Oceania Ã¨ 11769858.0

La media dei casi in Oceania Ã¨ 355420.45812

La percentuale dei casi in Oceania Ã¨ 0,4%


# VACCINI

EUROPA


Il min dei vaccini in Europe Ã¨ 0.0

Il max dei vaccini in Europe Ã¨ 192221468.0

La media dei vaccini in Europe Ã¨ 27275774.196870532

La percentuale dei vaccini in Europe Ã¨ 1.782823009422204


SUD AMERICA

Il min dei vaccini in South America Ã¨ 0.0


Il max dei vaccini in South America Ã¨ 486436436.0


La media dei vaccini in South America Ã¨ 65958353.543699816


La percentuale dei vaccini in South America Ã¨ 1.0501583501770269

OCEANIA


Il min dei vaccini in Oceania Ã¨ 0.0


Il max dei vaccini in Oceania Ã¨ 69306345.0


La media dei vaccini in Oceania Ã¨ 12617372.973786408


La percentuale dei vaccini in Oceania Ã¨ 0.0639019785567765

I continenti che hanno avuto piÃ¹ casi sono l'Europa e il Sud America, mentre l'Oceania ha avuto molti meno casi ma questo andrebbe confrontanto con la popolazione di ogni continente e vedere la percentuale rispetto la popolazione totale. Prestando attenzione alla percentuale di casi comparati con i casi mondiali, l'Europa Ã¨ stata piÃ¹ colpita rispetto al Sud America. Per quanto riguarda le vaccinazioni lo stato che ha somministrato piÃ¹ vaccini tra questi tre continenti Ã¨ il Sud America. Anche se controllanto le percentuali di tutti i vaccini effettuati nel mondo vediamo che l'Europa ha effetturato piÃ¹ vaccini, a seguire l'America Latina e in fine l'Oceania. Per valutare questi numeri si dovrebbe prendere in considerazione il numero della popolazione, l'Oceania ad esempio ha una popolazione nettamente inferiore all'Europa e al Sud America.